name: nsit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^1.3.0

  cupertino_icons: ^0.1.3
  flutter_bloc: ^2.1.1

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/Back.png
    - assets/images/progress.png
    - assets/images/a3.png
    - assets/images/p1.png
    - assets/images/a4.png
    - assets/images/a4.png
    - assets/images/logo.png
    - assets/images/g1.png
    - assets/images/g2.png
    - assets/images/g3.png
    - assets/images/g4.png
    - assets/images/100.png

  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf
      - family: Maiandra
        fonts:
          - asset: assets/Maiandra.ttf
